



const intro=document.getElementById("intro");
let heading=intro.getElementsByTagName("h3");

let myimg=document.getElementById("myimg");
myimg.src=("42737CC5-98FD-467C-85EE-C2050544DAC1_1_105_c.jpeg")


//ANIMATION
const elem=document.getElementById("animate");

function myMove(){
    let id=null;
    let pos=0;
    clearInterval(id);
    id=setInterval(frame,5); //her 5 ms de frami çağırır
    function frame(){
        if (pos==350){
            clearInterval(id); //animasyonu durduruyor

        }else{
            pos++;
            elem.style.top=pos+"px";
            elem.style.left=pos+"px";
        }
    }

}

/*
JS EVENTS
-----------

HTML events are things that happen to HTML elements.

Examples of events:

An HTML button is clicked
A web page has finished loading
The mouse moves over an element
A keyboard key is pressed
An HTML input field is changed

for html:
<button onclick="js codes or js function"></button>

common html events:
onchange
onclick
onmouseover
onmouseout
onkeydown
onload

Event handlers can be used to handle and verify user input, user actions, and browser actions:

Things that should be done every time a page loads
Things that should be done when the page is closed
Action that should be performed when a user clicks a button
Content that should be verified when a user inputs data
And more ...
Many different methods can be used to let JavaScript work with events:

HTML event attributes can execute JavaScript code directly
HTML event attributes can call JavaScript functions
You can assign your own event handler functions to HTML elements
You can prevent events from being sent or being handled

*/

//SOME HTML DOM REFERENCE 

//element properties and methods
//addEventListener() method keeps HTML AND JAAVASCRIPT seperated.
const div=document.getElementById("container");
div.after("added")




//so you can use js and addeventlistener and click or on html you can say onclik 

//mouse events
const buttonn=document.getElementById("anotherbutton");
buttonn.addEventListener("click",function(){
    buttonn.innerHTML="sude";

});

buttonn.addEventListener("mouseover",function(){
    buttonn.textContent="mouse over"
})

buttonn.addEventListener("mouseout",function(){
    buttonn.textContent="mouse out"
})

buttonn.addEventListener("mousemove", function (event) {
  document.getElementById("demo").innerHTML =
  "X: " + event.clientX + " Y: " + event.clientY;
});

//keyboard events

//event.key for values of the key. event.code for code of the key.

const key=document.getElementById("input")
const pressed=document.getElementById("key_val")


key.addEventListener("keydown", function(event){
    pressed.innerHTML="pressed key: "+event.key;
})



// Add Event Listener to document
document.addEventListener("DOMContentLoaded", function () {
  document.getElementById("demo").innerHTML = "HTML is loaded!";
});

//or if you want to check whether everything is loaded you should say "load".
//also, you can attach image or other sources to load.

//TIMING EVENTS

/*
Timing Events let you run code:

After a Delay
Or Repeatedly
Timing is driven by Timing Events generated by the system clock.

Timer Fuctions
Function	Description
setTimeout()	Sets a clock timeout (runs once)
setInterval()	Sets a clock interval (runs repeatedly)
clearTimeout()	Clears a timeout
clearInterval()	Clears an inteval

*/

setInterval(showtime,1000); //call show time every 1000 milisec
const time=document.getElementById("clock")
function showtime(){
    const d=new Date();
    time.innerHTML=d.getHours()+":"+d.getMinutes()
    
}

//The setTimeout() method executes a function after a delay in milliseconds.
//setTimeout(function, delay, p1,...,pN) //only function is required
// let btn listen for a click
document.getElementById("btn").addEventListener("click", function () {
// Then call showMsg after 2 seconds
  setTimeout(showMsg, 2000);
});

// Function to display message
function showMsg() {
  document.getElementById("demo2").innerHTML = "Hello after 2 seconds!";
}


